# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60af56ca3b59cb9037a741ccf7ee13cb6da2b59c74d1dcc2d9c1009e51dad731f1b3ffd785b47270121ec34049386fc94a79f1443e55ecf9ad9ba93ede65e000

test:
  secret_key_base: 4bd942629fc00d14f493a35b923289a16073af927eccd13ffe459300755dd313ccc7c25d57b436ba3d1f39b98d5b2a59440047732e03a78ea0724a3f7a7e4fb4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
